spring.application.name=SpringIDP

spring.datasource.url=jdbc:mysql://192.168.23.58:3306/idp_training_db
spring.datasource.username=root
spring.datasource.password=root

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

file.image-dir="C:\Users\Harv\source\repos\IDP Training\resources\images\"